
app_version: "1.0.0"

network:
  remote_host: 127.0.0.1
  remote_user: vunet
  current_node_ip: "216.48.191.10"
  port: 8086
 
paths:
  local_backups_dir: backups
  local_logs_dir: logs
  remote_binary_dir: /home/vunet/vuDataSim_bin/bin
  remote_conf_dir: /home/vunet/vuDataSim_bin
  remote_ssh_key: ~/.ssh/id_rsa
  static_dir: "./static"
process:
  default_timeout: 300
  graceful_shutdown_timeout: 10
  remote_timeout: 300
clickhouse:
  host: "e2e-83-212"
  port: 9000
  database: "vusmart"
  username: "monitoring_read"
  password: "StrongP@assword123"
monitoring_db:
  host: "e2e-83-212"
  port: 9000
  database: "monitoring"
  username: "monitoring_read"
  password: "StrongP@assword123"
truncate_db:
  host: "e2e-83-212"
  port: 9000
  database: "vusmart"
  username: "truncate_db"
  password: "StrongP@assword123"


kubernetes:
  default_namespace: "vsmaps"

database:
  path: "./data/vudatasim.db"
  max_connections: 10

postgres:
  host: "10.96.1.65"
  port: 5432
  user: "Load_Testing_Tool_read_user"
  password: "StrongPassword123"
  dbname: "multicore"
