sources:
  - name: "MongoDB"
    inputTopic:
      - name: "mongo-metrics-input"
    outputTopic:
      - name: "mongo-metrics"
      - name: "mongo-top-stats"
      - name: "mongo-shard-stats"
      - name: "mongo-col-stats"
      - name: "mongo-db-stats"
    clickhouseTables:
      - "vmetrics_mongo_metrics_performance_metrics_data"
      - "vmetrics_mongo_top_stats_performance_metrics_data"
      - "vmetrics_mongo_shard_stats_performance_metrics_data"
      - "vmetrics_mongo_col_stats_performance_metrics_data"
      - "vmetrics_mongo_db_stats_performance_metrics_data"
    pipeline:
      - "mongo-monitor"

  - name: "Mssql"
    inputTopic:
      - name: "mssql-telegraf"
    outputTopic:
      - name: "mssql-memory-clerks"
      - name: "mssql-database-io"
      - name: "mssql-net-response"
      - name: "mssql-hadr-replica"
      - name: "mssql-schedulers"
      - name: "mssql-requests"
      - name: "mssql-server-properties"
      - name: "mssql-performance"
      - name: "mssql-hadr-dbreplica"
      - name: "mssql-session"
      - name: "mssql-telegraf-health"
      - name: "mssql-volume-space"
      - name: "mssql-cpu"
      - name: "mssql-waitstats"
      - name: "mssql-cluster"
      - name: "mssql-recentbackup"
    clickhouseTables:
      - "vmetrics_mssql_monitor_memory_clerks_data"
      - "vmetrics_mssql_monitor_IO_statistics_data"
      - "vmetrics_mssql_monitor_net_response_data"
      - "vmetrics_mssql_monitor_hadr_replica_states_data"
      - "vmetrics_mssql_monitor_server_schedulers_data"
      - "vmetrics_mssql_monitor_server_requests_data"
      - "vmetrics_mssql_monitor_server_properties_data"
      - "vmetrics_mssql_monitor_server_performance_data"
      - "vmetrics_mssql_monitor_hadr_dbreplica_states_data"
      - "vmetrics_mssql_monitor_sql_session_data"
      - "vmetrics_mssql_monitor_telegraf_health_data"
      - "vmetrics_mssql_monitor_server_volume_space_data"
      - "vmetrics_mssql_monitor_server_cpu_data"
      - "vmetrics_mssql_monitor_server_waitstats_data"
      - "vmetrics_mssql_monitor_cluster_data"
      - "vmetrics_mssql_monitor_server_recent_backup_data"
    pipeline:
      - "mssql-telegraf-pipeline"

  - name: "Apache"
    inputTopic:
      - name: "apache-metrics-input"
    outputTopic:
      - name: "apache-logs"
      - name: "apache-metrics"
    clickhouseTables:
      - "vlogs_apachelogs_data"
      - "vmetrics_apachemetrics_data"
    pipeline:
      - "apache-metrics"

  - name: "LinuxMonitor"
    inputTopic:
      - name: "linux-monitor-input"
    outputTopic:
      - name: "linux-monitor-additional-metrics"
      - name: "linux-monitor-process-metrics"
      - name: "linux-monitor-resource-metrics"
      - name: "linux-monitor-storage-metrics"
    clickhouseTables:
      - "vmetrics_linux_monitor_additional_metrics_data"
      - "vmetrics_linux_monitor_process_metrics_data"
      - "vmetrics_linux_monitor_resource_metrics_data"
      - "vmetrics_linux_monitor_storage_metrics_data"
    pipeline:
      - "linuxmonitor"

  - name: "K8s"
    inputTopic:
      - name: "kubernetes-metrics-input"
    outputTopic:
      - name: "kubernetes-kubelet-metrics"
      - name: "kubernetes-kube-state-metrics"
      - name: "kubernetes-etcd-metrics"
      - name: "kubernetes-apiserver-metrics"
      - name: "kubernetes-controllermanager-metrics"
      - name: "kubernetes-scheduler-metrics"
      - name: "kubernetes-proxy-metrics"
    clickhouseTables:
      - "vmetrics_kubernetes_kubelet_metrics_data"
      - "vmetrics_kubernetes_kube_state_metrics_data"
      - "vmetrics_kubernetes_etcd_metrics_data"
      - "vmetrics_kubernetes_apiserver_metrics_data"
      - "vmetrics_kubernetes_controllermanager_metrics_data"
      - "vmetrics_kubernetes_scheduler_metrics_data"
      - "vmetrics_kubernetes_proxy_metrics_data"
    pipeline:
      - "kubernetes-metrics"
  

  - name: "AWS_ALB"
    inputTopic:
      - name: "aws-alb-metrics-input"
    outputTopic:
      - name: "aws-alb-metrics"
    clickhouseTables:
      - "vmetrics_aws_alb_metrics_data"
    pipeline:
      - "aws-alb-metrics"

  - name: "AzureStorageBlob"
    inputTopic:
      - name: "vuazure-storage-blob-input"
    outputTopic:
      - name: "vuazure-storage-blob-output"
    clickhouseTables:
      - "vmetrics_vuazure_storage_blob_output_data"
    pipeline:
      - "azure-storage-blob"

  - name: "BRUM"
    inputTopic:
      - name: "rum-input"
    outputTopic: []
    clickhouseTables:
      - "vtraces_rum_data"
    pipeline: []

  - name: "CiscoIoSSwitch"
    inputTopic:
      - name: "snmp-cisco-l3switch"
    outputTopic:
      - name: "snmp-network-element-health"
    clickhouseTables:
      - "vmetrics_snmp_network_element_health_data"
    pipeline:
      - "snmp-cisco-switch"

  - name: "Azure_Firewall"
    inputTopic:
      - name: "azure-firewall-input"
    outputTopic:
      - name: "azure-firewall-output"
    clickhouseTables:
      - "vmetrics_azure_firewall_data"
    pipeline:
      - "azure-firewall"

  - name: "DNS_Monitoring"
    inputTopic:
      - name: "dns-metrics-input"
    outputTopic:
      - name: "dns-metrics"
    clickhouseTables:
      - "vmetrics_dns_metrics_data"
    pipeline:
      - "dns-metrics"

  - name: "Azure_API_Management"
    inputTopic:
      - name: "azure-api-input"
    outputTopic:
      - name: "azure-api-output"
    clickhouseTables:
      - "vmetrics_azureapimetrics_data"
    pipeline:
      - "azure-api"

  - name: "IBMMQ"
    inputTopic:
      - name: "ibm-mq-metrics-input"
    outputTopic:
      - name: "ibm-mq-metrics-QueueMetrics"
      - name: "ibm-mq-metrics-ChannelMetrics"
      - name: "ibm-mq-metrics-QMGRMetrics"
    clickhouseTables:
      - "vmetrics_ibm_error_logs_data"
      - "vmetrics_ibm_mq_QueueMetrics_data"
      - "vmetrics_ibm_mq_ChannelMetrics_data"
      - "vmetrics_ibm_mq_QMGRMetrics_data"
    pipeline:
      - "ibm-mq-metrics"

  - name: "Azure_Redis_Cache"
    inputTopic:
      - name: "azure-redis-cache-input"
    outputTopic:
      - name: "azure-redis-cache-metrics"
    clickhouseTables:
      - "vmetrics_azure_redis_cache_metrics_data"
    pipeline:
      - "azure-redis-cache-pipeline"

  - name: "ServiceMonitor"
    inputTopic:
      - name: "servicebeat-metrics-input"
    outputTopic:
      - name: "servicebeat-metrics-output"
    clickhouseTables:
      - "vmetrics_servicemetrics_data"
    pipeline:
      - "servicebeat-availability"

  - name: "SyntheticBrowserMonitoring"
    inputTopic:
      - name: "synthetic-browserjourney-monitoring-insights"
    outputTopic: []
    clickhouseTables: 
      - "vlogs_synthetic_browserjourney_monitoring_insights_data"
    pipeline: []

  - name: "Tomcat"
    inputTopic:
      - name: "tomcat-metrics-input"
    outputTopic:
      - name: "tomcat-metrics"
    clickhouseTables:
      - "vmetrics_tomcatmetrics_data"
    pipeline:
      - "tomcat-metrics"

  - name: "WebLogic"
    inputTopic:
      - name: "weblogic-metrics-input"
    outputTopic:
      - name: "weblogic-metrics"
    clickhouseTables:
      - "vmetrics_weblogicmetrics_data"
    pipeline:
      - "weblogic-metrics"
  
  - name: "Traces"
    inputTopic:
      - name: "traces-input"
    outputTopic: []
    clickhouseTables:
      - "vtraces_metadata_data"
      - "vtraces_apm_span_data"
      - "vmetrics_apm_span_data"
    pipeline:
      - "traces-pipeline"